Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 1500

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
 Max: 20

Metrics/BlockLength:
  Max: 40

Naming/PredicateName:
 Enabled: false